name: Create a comment on a new issues

on:
  issues:
    types: [opened]
    
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{toJSON(github.event)}}' | jq
        shell: bash
        
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.1.1
        with:        
         issue-number: ${{(github.event.issue.number)}}         
         body: |
          komentar
         reactions: +1
