name: pomoz_Bog workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main            
    workflow_dispatch:
    
jobs:

 pozdrav:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v2
        - name: pomoz Bog
          run: echo "Pomoz Bog"
          shell: bash
                
 zbogom:
    runs-on: ubuntu-latest
    steps:
        - name: zbogom poz
          run: echo "Zbogom"
          shell: bash